{{- $name := include "ingress-gateway.name" . -}}
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: {{ $name }}-dnspolicy
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $name }}
    sectionName: {{ .Values.gateway.name | default "api" | quote }}
  providerRefs:
    - name: {{ $name }}-aws-credentials
  {{- if eq (default "loadbalanced" .Values.dns.routingStrategy) "loadbalanced" }}
  loadBalancing:
    weight: {{ .Values.dns.loadBalancing.weight | default 120 }}
    geo: {{ .Values.dns.loadBalancing.geoCode | default "" | quote }}
    defaultGeo: {{ .Values.dns.loadBalancing.defaultGeo | default false }}
  {{- end }}
  healthCheck:
    path: {{ .Values.dns.healthCheck.path | default "/health" | quote }}
    interval: {{ .Values.dns.healthCheck.interval | default "1m" | quote }}
    failureThreshold: {{ .Values.dns.healthCheck.failureThreshold | default 3 }}
